from fastapi import APIRouter, Depends, HTTPException
from typing import List
import logging
from ..schemas import TravelPlan
from ..models import TravelPlanModel
from ..db import get_session
from sqlmodel import select
from pydantic import BaseModel
from ..schemas import BasicInfo
from ..config import settings

router = APIRouter(prefix="/travel", tags=["travel"])

logger = logging.getLogger(__name__)


class CreatePlanIn(BaseModel):
    # frontend will only send basic_info matching the BasicInfo schema
    basic_info: BasicInfo


if settings.SUPABASE_URL:
    # Supabase-backed async endpoints
    from ..providers.supabase_client import list_plans as sb_list_plans, create_plan as sb_create_plan, update_plan as sb_update_plan, delete_plan as sb_delete_plan
    from ..auth_supabase import get_current_user
    from ..providers.llm_provider import plan_by_coza


    @router.get("/plans")
    async def list_plans(current_user=Depends(get_current_user)):
        user_id = current_user.get("id")
        return await sb_list_plans(user_id)


    @router.post("/plans")
    async def create_plan(payload: CreatePlanIn, current_user=Depends(get_current_user)):
        """Create a travel plan.

        Behavior:
        - Use the provided `basic_info` (from frontend) to call the Coze workflow and generate a TravelPlan.
        - Persist the generated plan to Supabase and return the created plan object.
        """
        user_id = current_user.get("id")

        # 1) Generate plan from LLM using the basic_info
        try:
            # pass a plain dict to plan_by_coza
            generated = await plan_by_coza(payload.basic_info.dict())
        except Exception as e:
            # Log full exception server-side for debugging and return a concise message to client
            logger.exception("Error while generating plan via Coze workflow")
            raise HTTPException(status_code=500, detail=f"Failed to generate plan: {e}")

        print(generated)
        # title is generated by Coze (frontend does not send it)
        title = generated.get("title")

        # 2) Persist generated plan (store full generated dict as payload.data)
        to_save = {"title": title, **generated}
        try:
            created = await sb_create_plan(user_id, to_save)
        except Exception as e:
            logger.exception("Error while saving generated plan to Supabase")
            raise HTTPException(status_code=500, detail=f"Failed to save plan: {e}")

        # sb_create_plan returns list of rows; return first created object for API compatibility
        if isinstance(created, list):
            return created[0] if created else {}
        return created


    @router.put("/plans/{plan_id}")
    async def update_plan(plan_id: int, payload: dict, current_user=Depends(get_current_user)):
        user_id = current_user.get("id")
        updated = await sb_update_plan(plan_id, user_id, payload)
        return updated


    @router.delete("/plans/{plan_id}")
    async def delete_plan(plan_id: int, current_user=Depends(get_current_user)):
        user_id = current_user.get("id")
        return await sb_delete_plan(plan_id, user_id)

else:
    # Fallback to local DB (synchronous)

    @router.get("/plans")
    def list_plans(session=Depends(get_session)):
        q = session.exec(select(TravelPlanModel)).all()
        return [{"id": p.id, **p.data} for p in q]


    @router.post("/plans")
    def create_plan(payload: CreatePlanIn, session=Depends(get_session)):
        # fallback local DB: synthesize a title from basic_info if missing
        basic = payload.basic_info
        try:
            title = f"{basic.destination}{basic.days}日行程"
        except Exception:
            title = "旅行计划"
        plan = TravelPlanModel(owner_id=0, title=title, data=payload.dict())
        session.add(plan)
        session.commit()
        session.refresh(plan)
        return {"id": plan.id, **plan.data}


    @router.put("/plans/{plan_id}")
    def update_plan(plan_id: int, payload: dict, session=Depends(get_session)):
        p = session.get(TravelPlanModel, plan_id)
        if not p:
            raise HTTPException(status_code=404, detail="Not found")
        p.data = payload
        session.add(p)
        session.commit()
        session.refresh(p)
        return {"id": p.id, **p.data}


    @router.delete("/plans/{plan_id}")
    def delete_plan(plan_id: int, session=Depends(get_session)):
        p = session.get(TravelPlanModel, plan_id)
        if not p:
            raise HTTPException(status_code=404, detail="Not found")
        session.delete(p)
        session.commit()
        return {"ok": True}
